### ISSUE TITLE
juristic probleme

### ISSUE THREAD

**Issue by B3yT** [Nabil-Lahssini/prayer_assistant#2]
![image](https://user-images.githubusercontent.com/85953451/151633518-89a73e89-b23c-4932-ba9f-68e14d94452d.png)
juristic dont change it's only shafii

**Comment by Nabil-Lahssini** [comment]
The issue doesn't depend on the prayer assistant repository. It is at the API level.
I will try to report the problem to the API owners. Thank you for your contribution !
